### ISSUE TITLE
What tool did you use to simplify the vectors?

### ISSUE THREAD

**Issue by sassansh** [sitrucp/canada_covid_health_regions#1]

**Comment by sitrucp** [comment]
Not sure which I used for this project but one of these:

https://mapshaper.org

or 

QGIS eg https://gis.stackexchange.com/questions/25914/smoothing-generalizing-polygon-in-qgis

I should add that to the write-up, thanks for asking!

**Comment by sassansh** [comment]
Awesome! Thank you ☺️
